name: restrict_raw_flutter
description: An analyzer plugin to restrict usage of Flutter's standard widgets and encourage using custom design system components.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer_plugin: ^0.13.11
  analyzer: ^9.0.0

dev_dependencies:
  analyzer_testing: ^0.1.7
  lints: ^6.0.0
  test: ^1.28.0
  test_reflective_loader: ^0.4.0
